[package]
authors = [
  "The Real Time For the Masses developers",
  "Jorge Aparicio <jorge@japaric.io>",
  "Per Lindgren <per.lindgren@ltu.se>",
]
categories = ["concurrency", "embedded", "no-std"]
description = "Real Time For the Masses (RTFM): a concurrency framework for building real time systems"
documentation = "https://rtfm.rs/"
edition = "2018"
keywords = ["arm", "cortex-m"]
license = "MIT OR Apache-2.0"
name = "cortex-m-rtfm"
readme = "README.md"
repository = "https://github.com/rtfm-rs/cortex-m-rtfm"
version = "0.5.1"

[lib]
name = "rtfm"

[[example]]
name = "baseline"
required-features = ["__v7"]

[[example]]
name = "periodic"
required-features = ["__v7"]

[[example]]
name = "pool"
required-features = ["__v7"]

[[example]]
name = "schedule"
required-features = ["__v7"]

[[example]]
name = "t-cfg"
required-features = ["__v7"]

[[example]]
name = "t-schedule"
required-features = ["__v7"]

[[example]]
name = "types"
required-features = ["__v7"]

[dependencies]
cortex-m = "0.6.2"
cortex-m-rtfm-macros = { path = "macros", version = "0.5.0" }
rtfm-core = "0.3.0"
imxrt1062-rt = { git = "https://github.com/mciantyre/teensy4-rs.git" }
heapless = "0.5.0"

[dependencies.microamp]
optional = true
version = "0.1.0-alpha.2"

[dev-dependencies]
lm3s6965 = "0.1.3"
panic-halt = "0.2.0"
cortex-m-semihosting = "0.3.3"

[dev-dependencies.panic-semihosting]
features = ["exit"]
version = "0.5.2"

[target.x86_64-unknown-linux-gnu.dev-dependencies]
trybuild = "1"

[features]
heterogeneous = ["cortex-m-rtfm-macros/heterogeneous", "microamp"]
homogeneous = ["cortex-m-rtfm-macros/homogeneous"]
# used for testing this crate; do not use in applications
__v7 =[]

[profile.release]
codegen-units = 1
lto = true

[workspace]
members = [
  "heterogeneous",
  "homogeneous",
  "macros",
]
